### ISSUE TITLE
disable zoom on double tap on ios devices

### ISSUE THREAD

**Issue by mathse** [phihag/bup#12]
can you implement this?
https://stackoverflow.com/questions/4389932/how-do-you-disable-viewport-zooming-on-mobile-safari

**Comment by phihag** [comment]
Sorry for the late reply. Is there a problem with a specific element? Than I'd rather fix that. As explained in [this answer](https://stackoverflow.com/a/38852262/35070) under the StackOverflow question, there does not seem to be a way to disable double tap zoom on iOS 10 and later.
