### ISSUE TITLE
Add a "service"-markup for view "stripes"

### ISSUE THREAD

**Issue by ppuschmann** [phihag/bup#15]
The view "stripes" uses the same colour for marking the set-winner and for current team/player at service.
There's no distinguished marker highlighting the current team/player at service.

I'd suggest to either change the background colour of the team serving or changing the foreground-colour to highlight the current serving side.

Similar highlighting is already implemented in the views "international" and "teamcourt".

**Comment by phihag** [comment]
Sorry for the late reply. Server indication is now implemented for the _stripes_ displaymode as well:

![image](https://user-images.githubusercontent.com/779568/60396701-2e19c400-9b45-11e9-84dc-5be643429e72.png)
