### ISSUE TITLE
code not run on localhost

### ISSUE THREAD

**Issue by isoftjhang** [phihag/bup#16]
This code can be run on localhost or not .. on xampp server its not installation yet.  can you explain methods how to install it.

**Comment by phihag** [comment]
Which error do you get?

bup is the umpire panel and display, i.e. the code that runs client-side. As such, it should work on any web server; just check out the repository into the root of your xampp installation and go there with your web browser. Actually, you don't even need a web server: If you open bup.html on your disk in a web browser, it should render just fine.

If you want to see bup in action, there are online demos; for instance, https://aufschlagwechsel.de/bup/#bldemo is a demo for the German Bundesliga (where bup is used in 29 of 30 clubs).

To really make use of bup in a real-world setting, you're going to need a server though, to store the match results, broadcast them to the world, and do further management. bup is integrated into multiple services (mainly for league matches); one of them is the open-source [bbt](https://github.com/phihag/bbt) for tournaments.

I'd be very happy to include bup in more services, or help you in setting that up. Just contact me via email, WhatsApp, Facebook or so. See https://phihag.de/ for my contact details.

**Comment by isoftjhang** [comment]
Thanks for your quick reply,   I already install xampp server and access using localhost but A blank page is appearing nothing . I also try to open direct HTML file and same thing appearing.  Only title Badminton Umpire Panel  show and favicon .. but nothing appear in body
