### ISSUE TITLE
Upload turnier.de not working

### ISSUE THREAD

**Issue by ppuschmann** [phihag/bup#38]
The dialogue for uploading / syncing information (after a matchday) to "turnier.de" returns a valid URL at "turnier.de" and is marked "successfully uploaded all information", but there's no information entered in the forms at "turnier.de"

expected behaviour: information is stored in "turnier.de" and results don't have to be entered manually

environment: Courtspot / bup
bup version: 2022.09.10.0232ddbced5

**Comment by mathse** [comment]
same here

**Comment by phihag** [comment]
@ppuschmann You closed this issue. Does it work again for you?

**Comment by ppuschmann** [comment]
No, but I only have a minimum amount of hope for a solution. 

No offence intended. 

I only think that a "solution" with turnier.de is not really possible and I wanted to clean up some tickets in GH, also removing some long-lasting tickets from your shoulders 😀
