### ISSUE TITLE
Make file not working

### ISSUE THREAD

**Issue by Julian-Heidenreich** [phihag/bup#39]
# Issue

I just tried to run "make deps" and I get an error because of the node-webcrypto-ossl package.
It is desecrated since Node 15 and wont download/install with node install anymore. I needed to remove the dependencies and after that everything is installing normal

https://www.npmjs.com/package/node-webcrypto-ossl

-------------------------------

And there are security vulnerabilities in many packages. I am not sure if that is relevant.

# npm audit report

ansi-regex  3.0.0 || 4.0.0 - 4.1.0 || 5.0.0
Severity: high
Inefficient Regular Expression Complexity in chalk/ansi-regex - https://github.com/advisories/GHSA-93q8-gq69-wqmw
Inefficient Regular Expression Complexity in chalk/ansi-regex - https://github.com/advisories/GHSA-93q8-gq69-wqmw
Inefficient Regular Expression Complexity in chalk/ansi-regex - https://github.com/advisories/GHSA-93q8-gq69-wqmw
fix available via `npm audit fix`
node_modules/ansi-regex
node_modules/cliui/node_modules/ansi-regex
node_modules/table/node_modules/ansi-regex
node_modules/wide-align/node_modules/ansi-regex
node_modules/wrap-ansi/node_modules/ansi-regex
node_modules/yargs/node_modules/ansi-regex

async  3.0.0 - 3.2.1
Severity: high
Prototype Pollution in async - https://github.com/advisories/GHSA-fwr7-v2mv-hh25
fix available via `npm audit fix`
node_modules/async

jszip  3.0.0 - 3.6.0
Severity: moderate
Prototype Pollution - https://github.com/advisories/GHSA-jg8v-48h5-wgxg
fix available via `npm audit fix`
node_modules/jszip

minimatch  <3.0.5
Severity: high
minimatch ReDoS vulnerability - https://github.com/advisories/GHSA-f8q6-p94x-37v3
fix available via `npm audit fix`
node_modules/minimatch
  mocha  5.1.0 - 9.2.1
  Depends on vulnerable versions of minimatch
  Depends on vulnerable versions of nanoid
  node_modules/mocha

minimist  <1.2.6
Severity: critical
Prototype Pollution in minimist - https://github.com/advisories/GHSA-xvch-5gv4-984h
fix available via `npm audit fix`
node_modules/minimist

nanoid  3.0.0 - 3.1.30
Severity: moderate
Exposure of Sensitive Information to an Unauthorized Actor in nanoid - https://github.com/advisories/GHSA-qrpm-p2h7-hrv2
fix available via `npm audit fix`
node_modules/nanoid

node-fetch  <2.6.7
Severity: high
node-fetch is vulnerable to Exposure of Sensitive Information to an Unauthorized Actor - https://github.com/advisories/GHSA-r683-j2x4-v87g
fix available via `npm audit fix`
node_modules/node-fetch

nth-check  <2.0.1
Severity: high
Inefficient Regular Expression Complexity in nth-check - https://github.com/advisories/GHSA-rp65-9cf3-cjxr
fix available via `npm audit fix`
node_modules/nth-check
  css-select  <=3.1.0
  Depends on vulnerable versions of nth-check
  node_modules/css-select
    svgo  1.0.0 - 1.3.2
    Depends on vulnerable versions of css-select
    node_modules/svgo

path-parse  <1.0.7
Severity: moderate
Regular Expression Denial of Service in path-parse - https://github.com/advisories/GHSA-hj48-42vr-x3v9
fix available via `npm audit fix`
node_modules/path-parse

xmldom  *
Severity: critical
Misinterpretation of malicious XML input - https://github.com/advisories/GHSA-5fg8-2547-mr8q
xmldom allows multiple root nodes in a DOM - https://github.com/advisories/GHSA-crh6-fp67-6883
No fix available
node_modules/xmldom

13 vulnerabilities (3 moderate, 8 high, 2 critical)

To address issues that do not require attention, run:
  npm audit fix

Some issues need review, and may require choosing
a different dependency.

**Comment by phihag** [comment]
As a workaround, you can run `make deps-essential`. Since these packages are for dev only, security is not really an issue. Nevertheless, I'll have a look at updating them.

**Comment by Julian-Heidenreich** [comment]
In the information about the node-webcrypto-ossl is that node 15 has the functions built in maybe change to that. Some deps already need node 14^ anyways :)

**Comment by phihag** [comment]
Fixed, for now just removing node-webcrypto-ossl – it was only used for tests anyways.

**Comment by phihag** [comment]
@Julian-Heidenreich I can't find your email, you have no public contributions on GitHub (only with the web interface it seems?). Please message me at phihag@phihag.de .

You can now test bup with

```
docker build . --tag bup && docker run --rm -p 8028:80 -it bup
```
bup then working on http://localhost:8028/bup.html proves that the build system works. If it doesn't for you, please review the `Dockerfile` and compare those commands to the ones on your system.
